// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace group3Database.Models
{
    public partial class ClassTable
    {
        public ClassTable()
        {
            ClassSchedules = new HashSet<ClassSchedule>();
            StudentClasses = new HashSet<StudentClass>();
        }

        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public int InstructorId { get; set; }
        public int ClassMaxSize { get; set; }
        public int RoomId { get; set; }
        public DateTime ClassStartDate { get; set; }
        public DateTime ClassEndDate { get; set; }
        public DateTime ClassWithdrawEndDate { get; set; }
        public DateTime ClassDropEndDate { get; set; }

        public virtual Course Course { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<ClassSchedule> ClassSchedules { get; set; }
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
    }
}