// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace group3Database.Models
{
    public partial class ClassSchedule
    {
        public int ClassId { get; set; }
        public string WeekDayId { get; set; }
        public TimeSpan ClassSchTime { get; set; }

        public virtual ClassTable Class { get; set; }
        public virtual WeekDay WeekDay { get; set; }
    }
}