// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace group3Database.Models
{
    public partial class Course
    {
        public Course()
        {
            ClassTables = new HashSet<ClassTable>();
        }

        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
        public byte CourseCredits { get; set; }
        public int SubjectId { get; set; }

        public virtual Subject Subject { get; set; }
        public virtual ICollection<ClassTable> ClassTables { get; set; }
    }
}