// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace group3Database.Models
{
    public partial class Room
    {
        public Room()
        {
            ClassTables = new HashSet<ClassTable>();
        }

        public int RoomId { get; set; }

        public virtual ICollection<ClassTable> ClassTables { get; set; }
    }
}